GET http://127.0.0.1:10001/movies/
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?director_id=12
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?genre_id=4
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?year=2010
Accept: application/json

###

GET http://127.0.0.1:10001/directors/
Accept: application/json

###

GET http://127.0.0.1:10001/directors/1
Accept: application/json

###

GET http://127.0.0.1:10001/genres/
Accept: application/json

###

GET http://127.0.0.1:10001/genres/1
Accept: application/json

###

GET http://127.0.0.1:10001/movies/21
Accept: application/json

###

POST http://127.0.0.1:5000/movies/
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IkdlbmVyYWwiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NjA0MDY0NDZ9.HRBu6DTQ4M6vpIAg9VL_U_-Kjnhoqe10ccKqioCN7l8

{
  "title": "Гарри Поттер мой кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1990,
  "rating": 10,
  "description": "10 из 10!"
}

###

PUT http://127.0.0.1:10001/movies/21
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

PATCH http://127.0.0.1:10001/movies/3
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:10001/movies/21

###

POST http://127.0.0.1:5000/users/
Accept: application/json
Content-Type: application/json

{
  "username" : "General",
  "password" : "pass7",
  "role" : "admin"
}

###

DELETE http://127.0.0.1:5000/users/6

###

GET http://127.0.0.1:5000/users/
Accept: application/json
Content-Type: application/json

###
POST http://127.0.0.1:5000/genres/
Accept: application/json
Content-Type: application/json

{
  "name" : "test"
 }

###
DELETE http://127.0.0.1:5000/genres/19

###
POST http://127.0.0.1:5000/auth/
Accept: application/json
Content-Type: application/json

{
  "username" : "General",
  "password" : "pass7"
}
###

PUT http://127.0.0.1:5000/auth/
Accept: application/json
Content-Type: application/json

{
  "refresh_token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ik5hdGFzaGEiLCJyb2xlIjoiZ2lybCIsImV4cCI6MTY2Mjk5MjE5MX0.laBiXCy_necAS9fGdZg2wUp_vXkudOGLt6qau185d3Q"

}

###
GET http://127.0.0.1:5000/movies/2
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ik5hdGFzaGEiLCJyb2xlIjoiZ2lybCIsImV4cCI6MTY2Mjk5MjE5MX0.laBiXCy_necAS9fGdZg2wUp_vXkudOGLt6qau185d3Q

###